fix a crash in FieldIterator::next() (#13523)
* fix a crash in FieldIterator::next()

FieldIterator::next() unconditionally subtracts a value of 2 from the
end of its `_stack` member, which can make the operation point before
the beginning of the `_stack` storage of `_stack` has less than 2
members.
There is a follow-up check to check if the subtracted value is at least
a big as `_stack.begin()`, but this may be too late.
Using a debug STL build (`_GLIBCXX_DEBUG`) already crashes when
subtracting 2 from the container's end:

```
2021-02-10T01:28:38.955Z [============] runInArangod: Trying tests/js/server/aql/aql-arangosearch-count-optimization.js ...
/usr/include/c++/10/debug/safe_iterator.h:924:
In function:
    __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<arangodb::iresearch::FieldIterator::Level*,
    std::__cxx1998::vector<arangodb::iresearch::FieldIterator::Level,
    std::allocator<arangodb::iresearch::FieldIterator::Level> > >,
    std::__debug::vector<arangodb::iresearch::FieldIterator::Level>,
    std::random_access_iterator_tag>::_Self __gnu_debug::operator-(const
    _Self&,
    __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<arangodb::iresearch::FieldIterator::Level*,
    std::__cxx1998::vector<arangodb::iresearch::FieldIterator::Level,
    std::allocator<arangodb::iresearch::FieldIterator::Level> > >,
    std::__debug::vector<arangodb::iresearch::FieldIterator::Level>,
    std::random_access_iterator_tag>::difference_type)

Error: attempt to retreat a past-the-end iterator 2 steps, which falls
outside its valid range.

Objects involved in the operation:
    iterator @ 0x0x7f09585f93e0 {
      type = __gnu_cxx::__normal_iterator<arangodb::iresearch::FieldIterator::Level*, std::__cxx1998::vector<arangodb::iresearch::FieldIterator::Level, std::allocator<arangodb::iresearch::FieldIterator::Level> > > (mutable iterator);
      state = past-the-end;
      references sequence with type 'std::__debug::vector<arangodb::iresearch::FieldIterator::Level, std::allocator<arangodb::iresearch::FieldIterator::Level> >' @ 0x0x7f09585f9850
    }
```

* added CHANGELOG entry

* use pointers instead of iterators

Co-authored-by: Andrey Abramov <andrey@arangodb.com>